# Generated by Django 5.2 on 2025-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, upload_to='20250601170248/images/'),
        ),
    ]
