# Generated by Django 5.2 on 2025-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, upload_to='20250601180720/images/'),
        ),
    ]
