# Generated by Django 5.2.3 on 2025-07-19 12:45

import design.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_category_options_category_level_category_lft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='custom_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='utilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(null=True, upload_to=design.models.design_image_path),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('norm_description', models.TextField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='design.design')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
