# Generated by Django 5.2.3 on 2025-07-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_design_added_by_design_custom_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['bom_position']},
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='count',
            new_name='bom_count',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='design',
            new_name='bom_design',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='link',
            new_name='bom_link',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='material',
            new_name='bom_material',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='name',
            new_name='bom_name',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='norm_description',
            new_name='bom_norm_description',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='notes',
            new_name='bom_notes',
        ),
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='position',
            new_name='bom_position',
        ),
    ]
