# Generated by Django 5.2.3 on 2025-07-29 16:03

import design.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_alter_billofmaterials_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='bom_norm_description',
        ),
        migrations.RemoveField(
            model_name='design',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='bom_standard',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='modified_from',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='techdraw',
            field=models.ImageField(null=True, upload_to=design.models.design_techdraw_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
    ]
