# Generated by Django 5.2.3 on 2025-07-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_remove_billofmaterials_bom_norm_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='custom_section',
            new_name='example',
        ),
    ]
