# Generated by Django 5.2.3 on 2025-08-04 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_rename_custom_section_design_example'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='created_by',
            field=models.ForeignKey(help_text='Add name of creator/modifier of new design', on_delete=django.db.models.deletion.CASCADE, related_name='created_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='modified_from',
            field=models.URLField(blank=True, help_text='URL of LoD Design to determine predecessor', null=True),
        ),
    ]
