# Generated by Django 5.2.3 on 2025-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_alter_design_created_by_alter_design_modified_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='production_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
