# Generated by Django 5.2.3 on 2025-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_design_production_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='custom_creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
