# Generated by Django 5.2.3 on 2025-08-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_design_custom_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='techdraw_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
