# Generated by Django 5.2.3 on 2025-08-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_design_image_list_design_techdraw_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image_list',
        ),
        migrations.RemoveField(
            model_name='design',
            name='techdraw_list',
        ),
    ]
