# Generated by Django 5.2.3 on 2025-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_remove_design_image_list_remove_design_techdraw_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='techdraw_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='bom_standard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
