# Generated by Django 5.2.3 on 2025-08-05 12:54

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_design_image_list_design_techdraw_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='design',
            name='example',
            field=models.TextField(default='No example provided'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(default='No image provided', upload_to=design.models.design_image_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='module',
            field=models.TextField(default='No module provided'),
        ),
    ]
