# Generated by Django 5.2.3 on 2025-08-07 10:45

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_alter_design_description_alter_design_example_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='example',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='module',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='techdraw',
            field=models.FileField(blank=True, null=True, upload_to=design.models.design_techdraw_path),
        ),
    ]
