# Generated by Django 5.2.3 on 2025-08-07 15:00

import design.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_alter_design_example_alter_design_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(default='No image provided', storage=django.core.files.storage.FileSystemStorage(base_url='/lod_content/tmp/', location='/home/lod/lod/lod_content/tmp'), upload_to=design.models.design_image_path),
        ),
        migrations.AlterField(
            model_name='design',
            name='techdraw',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/lod_content/tmp/', location='/home/lod/lod/lod_content/tmp'), upload_to=design.models.design_techdraw_path),
        ),
    ]
