# Generated by Django 5.2.3 on 2025-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_alter_design_image_alter_design_techdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(),
        ),
    ]
