# Generated by Django 5.2.3 on 2025-08-12 11:58

import design.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0016_alter_design_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/lod_content/tmp/', location='/home/lod/lod/lod_content/tmp'), upload_to=design.models.design_image_path),
        ),
    ]
