# Generated by Django 5.2.3 on 2025-08-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_alter_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500, null=True),
        ),
    ]
