# Generated by Django 5.2.3 on 2025-08-21 19:05

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_design_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='tags',
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add tags separated by commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
