# Generated by Django 5.2.3 on 2025-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_remove_design_tags_design_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='costs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
