# Generated by Django 5.2.3 on 2025-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_alter_design_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='standardization',
            field=models.TextField(blank=True, help_text='ISO/GPS norm of design', null=True),
        ),
    ]
