# Generated by Django 5.2.3 on 2025-08-20 17:53

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['position', 'name'], 'verbose_name_plural': 'Forum Categories'},
        ),
        migrations.RenameField(
            model_name='forumcategory',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='level',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='lft',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='rght',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sticky', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sticky', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.topic')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumTopic',
        ),
    ]
