# Generated by Django 5.2 on 2025-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, upload_to='thing_images'),
        ),
    ]
