# Generated by Django 5.2 on 2025-05-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_alter_thing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='is_sold',
            new_name='is_modified',
        ),
    ]
