# Generated by Django 5.2 on 2025-05-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0003_rename_is_sold_thing_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, upload_to='<django.db.models.fields.BigAutoField>/'),
        ),
    ]
