# Generated by Django 5.2 on 2025-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0004_alter_thing_id_alter_thing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(blank=True, upload_to='20250531175255/'),
        ),
    ]
